2018-09-07 12:43:04,198 ERROR: Exception on /user/ebullen [GET] [in c:\anaconda3\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\python\flask\base\app\routes.py", line 106, in user
    return render_template('user.html')
  File "c:\anaconda3\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\anaconda3\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\anaconda3\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\anaconda3\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\python\flask\base\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\python\flask\base\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\python\flask\base\app\templates\base.html", line 65, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\python\flask\base\app\templates\user.html", line 11, in block "app_content"
    <td width="256px"> <img src="{{ user.avatar(128) }}"></td>
  File "c:\anaconda3\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
